default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: sprout_development
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "sprout" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "sprout" } %>

test:
  <<: *default
  database: sprout_test
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "sprout" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "sprout" } %>

production:
  primary:
    <<: *default
    database: sprout_production
  cache:
    <<: *default
    database: sprout_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: sprout_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: sprout_production_cable
    migrations_paths: db/cable_migrate
